### ISSUE TITLE
Use SVG with pure-colour background

### ISSUE THREAD

**Issue by GrimPixel** [Destaq/wallpaper-learn#12]
I tried the example, the Chinese one. It takes 122 MB for 153 words.
If set the background to pure colour, then SVG is acceptable.

**Comment by Destaq** [comment]
Could you please be a bit clearer? I'm not sure what you are asking here @GrimPixel.

**Comment by GrimPixel** [comment]
Currently, it generates background with images, so the total size of a set is taking a large amount of space. If I don't want to see any image, can accept seeing a pure-coloured wallpaper, then it can be done with SVG, which is editable with a text editor and only has a few lines.

**Comment by Destaq** [comment]
Well unfortunately as far as I have know, this is not possible - most major operating systems don't support setting SVG wallpapers. Perhaps consider storing your wallpapers on a removable disk or compressing them with JPEG.
